# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpcloudCli < Formula
  desc "CLI tool for managing UpCloud services."
  homepage "https://upcloud.com/"
  version "3.9.0"
  license "MIT"

  depends_on "bash-completion" => :optional

  on_macos do
    on_intel do
      url "https://github.com/UpCloudLtd/upcloud-cli/releases/download/v3.9.0/upcloud-cli_3.9.0_darwin_x86_64.tar.gz"
      sha256 "31ff68d6c5b58e7658ee066675db69433643d1c49636d271992a8a418948e902"

      def install
        bin.install "upctl"
        #
      end
    end
    on_arm do
      url "https://github.com/UpCloudLtd/upcloud-cli/releases/download/v3.9.0/upcloud-cli_3.9.0_darwin_arm64.tar.gz"
      sha256 "141a7ae173c0a76d5e06ff1e069eac3f4736543442f4a4d8fceea79a631211b0"

      def install
        bin.install "upctl"
        #
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UpCloudLtd/upcloud-cli/releases/download/v3.9.0/upcloud-cli_3.9.0_linux_x86_64.tar.gz"
        sha256 "91ffddeaeb8af509eb34b2babb33a6aee53659cff9f1ec21a5355d51b3c776a4"

        def install
          bin.install "upctl"
          #
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UpCloudLtd/upcloud-cli/releases/download/v3.9.0/upcloud-cli_3.9.0_linux_arm64.tar.gz"
        sha256 "d7758e161f0668c8421ba5d0093bf22f124b4c134b81e8145a7e98511775e203"

        def install
          bin.install "upctl"
          #
        end
      end
    end
  end

  head "https://github.com/UpCloudLtd/upcloud-cli.git"

  test do
    system "#{bin}/upctl version"
  end
end
